### ISSUE TITLE
brew installation fail: macOS BigSur 11.1, M1 chip

### ISSUE THREAD

**Issue by polgreen** [moves-rwth/homebrew-storm#4]
Hi, 

I ran the following commands:
~~~
brew tap moves-rwth/storm
brew install stormchecker
~~~
And got the following error:
~~~
==> ./configure --prefix=/opt/homebrew/Cellar/cln/1.3.6
==> make
Last 15 lines from /Users/elipol/Library/Logs/Homebrew/cln/02.make:
uint32 mulu32_high;
       ^
./base/cl_low.h:210:21: note: declared with C language linkage here
  extern "C" uint32 mulu32_high;                        // -> High-Teil
                    ^
base/low/cl_low_mul.cc:57:8: error: declaration of 'mulu64_high' in global scope conflicts with declaration with C language linkage
uint64 mulu64_high;
       ^
./base/cl_low.h:354:21: note: declared with C language linkage here
  extern "C" uint64 mulu64_high;                        // -> High-Teil
                    ^
2 errors generated.
make[1]: *** [base/low/cl_low_mul.lo] Error 1
libtool: compile:  clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../autoconf -I../include -I../src -I../include -I../src -g -O2 -c base/output/cl_output_dec.cc -o base/output/cl_output_dec.o >/dev/null 2>&1
make: *** [all-recursive] Error 
~~~

Any ideas?

**Comment by polgreen** [comment]
Ah, I think the problem might be that cln, ginac and possibly a couple of other dependencies don't support apple silicon. Nevermind, I guess this is not easily solveable

**Comment by tquatmann** [comment]
Yes, it indeed does look like some libraries we use are not apple silicon ready. Unfortunately, we don't have such a machine  in our hands right now so we can not test this ourselves (yet).

Meanwhile, I know that at least one user was able to build storm from source through Rosetta (x86 simulation). You can probably follow [these](https://www.stormchecker.org/documentation/obtain-storm/build.html) steps and prefix appropriate commands with `arch -x86_64`.
This is, of course, slightly more involved than homebrew. If you need further information, please lete me know.

**Comment by janerjak** [comment]
Storm currently does not have native M1 mac support. However, I was successfully able to install storm through Rosetta 2 on my M1 mac. For this, run the commands:
`arch -x86_64 brew tap moves-rwth/storm`
`arch -x86_64 brew install stormchecker`
Note that this might take a while. The main build step took 15 minutes without any console output for me. On the first run I received an assertion error building boost, but once I killed all build processes in Activity Monitor and ran the above commands again, I was able to successfully build storm using brew.
You can then find your storm installation using
`arch -x86_64 brew --prefix stormchecker`
The main executable is at this path in the bin/ subdirectory. Feel free to directly answer, if any issues occur.

Just as a note: Running storm through Rosetta 2 is not tested to a great extent. However, I was able to successfully run the G-Test-Suite.

**Comment by tquatmann** [comment]
We now added a [section on our website](https://www.stormchecker.org/documentation/obtain-storm/homebrew.html) which details the necessary steps.

**Comment by eshitazaman** [comment]
@janerjak @tquatmann Hello, could you elaborate on how you were able to run the G-Test-Suite? I believe my installation gets stuck there. I've been following the instructions on the [website](https://www.stormchecker.org/documentation/obtain-storm/homebrew.html), and when I run `arch -x86_64 $X86_BREW install stormchecker` I get the error:
```
==> Installing moves-rwth/storm/stormchecker dependency: moves-rwth/misc/ca
==> cmake /private/tmp/carl-20211204-5587-yvjr0d/carl-c-14-20.09 -DEXPORT_TO_CMA
==> make install
Last 15 lines from /Users/eshitazaman/Library/Logs/Homebrew/carl/02.make:
Consolidate compiler generated dependencies of target gtest
[ 50%] Built target gtest
[ 75%] Building CXX object googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[100%] Linking CXX static library libgtest_main.a
[100%] Built target gtest_main
cd /tmp/carl-20211204-5587-1vcy6kg/resources/src/GTest-EP-build && /usr/local/bin/homebrew/Cellar/cmake/3.22.0/bin/cmake -E touch /tmp/carl-20211204-5587-1vcy6kg/resources/src/GTest-EP-stamp/GTest-EP-build
[ 24%] No install step for 'GTest-EP'
cd /tmp/carl-20211204-5587-1vcy6kg/resources/src/GTest-EP-build && /usr/local/bin/homebrew/Cellar/cmake/3.22.0/bin/cmake -E echo_append
cd /tmp/carl-20211204-5587-1vcy6kg/resources/src/GTest-EP-build && /usr/local/bin/homebrew/Cellar/cmake/3.22.0/bin/cmake -E touch /tmp/carl-20211204-5587-1vcy6kg/resources/src/GTest-EP-stamp/GTest-EP-install
[ 24%] Completed 'GTest-EP'
/usr/local/bin/homebrew/Cellar/cmake/3.22.0/bin/cmake -E make_directory /tmp/carl-20211204-5587-1vcy6kg/CMakeFiles
/usr/local/bin/homebrew/Cellar/cmake/3.22.0/bin/cmake -E touch /tmp/carl-20211204-5587-1vcy6kg/CMakeFiles/GTest-EP-complete
/usr/local/bin/homebrew/Cellar/cmake/3.22.0/bin/cmake -E touch /tmp/carl-20211204-5587-1vcy6kg/resources/src/GTest-EP-stamp/GTest-EP-done
[ 24%] Built target GTest-EP
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

```

**Comment by janerjak** [comment]
Hello. I recently had to reinstall storm on my M1 Pro and it didn’t seem like the website instructions we wrote still work everytime. I eventually got it working again, so I will try my best to help you out. Some questions:

- Where is your `$X86_BREW` installation? For me compilation only started working once I had installed homebrew using the main script in `/usr/local`. My untar anywhere installation in `/usr/local/homebrew` did also fail building storm at the CaRL / GiNAC stage.
- Did you use the “untar anywhere” method or the main installation script from brew.sh?
- Did you install all dependencies using `arch -x86_64 $X86_BREW install cln ginac automake cmake boost gmp glpk hwloc z3 xerces-c`?

The easiest thing you can try is installing Xcode from the App Store alongside CLT. For some reason homebrew then didn’t have to build everything from scratch. Make sure to reboot, after you have installed both suites (and possibly reinstalled homebrew using the main script).

If you did all these steps and it still won’t compile: from your output it seems like gtest is failed to be built in the build step of CArL. You could try building CArL from scratch yourself. Usually homebrew (or cmake for that matter) should pick the resulting library binary up. Also compiling it on your own results in more debug output presented in the terminal, although this is not as user friendly. Instructions for this are as follows:

Use homebrew to install latest x86 versions of cmake and clang(++) by typing: `arch -x86_64 $X86_BREW install cmake llvm`
Find clang and clang++. They are usually located in `/usr/local/opt/llvm/bin/`. You can also find the parent path of llvm using `arch -x86_64 $X86_BREW --prefix llvm`.
Navigate to a folder where you have access permissions and perform:

```
git clone -b master14 https://github.com/smtrat/carl
cd carl
mkdir build
cd build
arch -x86_64 /usr/local/bin/cmake -DUSE_CLN_NUMBERS=ON -DUSE_GINAC=ON -DTHREAD_SAFE=ON -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++ ..
arch -x86_64 make lib_carl -j8
```

Before using /usr/local and installing Xcode, I had weird autoconf issues when compiling CaRL in the GiNAC or main build step. If you receive the same, please reply.

Maybe this will show detailed error messages and we can figure out what causes the issue from there. I have attached my terminal output when performing these steps [terminal-output.zip](https://github.com/moves-rwth/homebrew-storm/files/7656469/terminal-output.zip). As a very last resort, you could also try building storm without homebrew for the maximum amount of debug info, but this might be a bit involved if errors occur. I have also attached terminal output for this, as this might be helpful. Hopefully it will work soon!

If it still doesn’t work or there are more questions, don’t hesitate to contact me.

**Comment by eshitazaman** [comment]
@janerjak Thanks for your detailed response and the terminal output.

Before your suggestions, I was using `$X86_BREW = usr/local/bin/homebrew/bin/brew` (just chose a random path different from that of the default brew installation). After hearing from you, I installed Homebrew into `/usr/local` (so now my `$X86_BREW` has value `/usr/local/bin/brew`. I've been following [these instructions](https://docs.brew.sh/Installation#multiple-installations) to make an additional installation by extracting the tarball (I assume this is what you mean by "“untar anywhere” method").

I already have a main installation of Homebrew that is located in `/opt/homebrew/bin/brew`, which I understand is the default installation location in M1-chip Macbooks. When I try to use the Homebrew installation in `/usr/local`, e.g. when I run `arch -x86_64 $X86_BREW install cmake llvm`, I get the error: `Error: /usr/local is not writable. You should change the ownership and permissions of /usr/local (etc...)` and when I try to do that, I get the error: `chown: /usr/local: Operation not permitted`.

I want to avoid the errors at the CaRL / GiNAC stage, altogether, by having Homebrew installed in `/usr/local`, per your suggestion (in the first bullet point). How were you able to have a working Homebrew installation in `/usr/local` on a M1-chip Macbook that can install packages? By the way, my OS version is 12.0 (Monterey).

**Comment by tquatmann** [comment]
The `Operation not permitted` seems to be a [common issue](https://stackoverflow.com/questions/46459152/cant-chown-usr-local-for-homebrew-in-mac-os-x-10-13-high-sierra).
You might also want to try to go to `Settings > Security & Privacy > Privacy > Full Disk Access` and add the terminal in there (not sure if this is actually related).

Stepping a step back, it's a bit unusual that there is absolutely no error message in the output. However, we're only seeing the last 15 lines:

```
Last 15 lines from /Users/eshitazaman/Library/Logs/Homebrew/carl/02.make:
```

Could you send us the complete output you get?

**Comment by eshitazaman** [comment]
@tquatmann @janerjak Thank you both! I was able to run storm successfully by installing homebrew per @janerjak's last comment, but when I tried to work with the C++ API (specifically, with this [starter project](https://github.com/moves-rwth/storm-project-starter-cpp)), I still got errors about 3rd party resources missing. I'm attaching the output of the `cmake ..` step ([terminal_output.txt](https://github.com/moves-rwth/homebrew-storm/files/7689231/terminal_output.txt)). The only subdirectories inside the `3rdparty` directory are `sparsepp` and `StormEigen`.

On that note, I read somewhere that in order to get more 3rd party resources installed, I'd need to install storm from source. Following [these](https://www.stormchecker.org/documentation/obtain-storm/build.html) instructions, when running `make`, I got the following error:
```
[  2%] Performing build step for 'cudd3'
CMake Error at /Users/eshitazaman/storm/build/resources/3rdparty/cudd-3.0.0/src/cudd3-stamp/cudd3-build-RELEASE.cmake:49 (message):
  Command failed: 2

   'make' 'CFLAGS=-O3 -w -DPIC -DHAVE_IEEE_754 -fno-common -ffast-math -fno-finite-math-only -march=native'

  See also

    /Users/eshitazaman/storm/build/resources/3rdparty/cudd-3.0.0/src/cudd3-stamp/cudd3-build-*.log


make[2]: *** [resources/3rdparty/cudd-3.0.0/src/cudd3-stamp/cudd3-build] Error 1
make[1]: *** [CMakeFiles/cudd3.dir/all] Error 2
make: *** [all] Error 2
```

Here is the error log file: [cudd3-build-err.log](https://github.com/moves-rwth/homebrew-storm/files/7689266/cudd3-build-err.log)

**Comment by tquatmann** [comment]
Yes, I think you'll need an installation from source for the API.

Please try checking out the `master` branch (and not the `stable` branch). The `cudd` issue should hopefully be fixed in `master`.

**Comment by eshitazaman** [comment]
Hi Tim,

I have built storm from source, got all the 3rdparty resources installed
too. But when I tried to build the C++ example project:
storm-project-starter-cpp, I got an error after running make. I am
attaching the error log here. Can you please help me to fix that?

Thanks,
Eshita

**Comment by tquatmann** [comment]
Hi Eshita, I did not get an attachment.

**Comment by eshitazaman** [comment]
Hi Tim,

The attachment is showing in my email. I can upload them on the cloud and
send you the links once I back on my computer.

Thanks,
Eshita

**Comment by eshitazaman** [comment]
Hi Tim,

Here is the link. Can you please check if you can access them.
https://iastate.box.com/s/garkpspc87rjvkcw9qf8kv4rfjwqlfrg

Thanks,
Eshita

**Comment by tquatmann** [comment]
Yes, now I got the attachments. Github doesn't seem to include them when sending emails.

I don't have much experiments with ARM Macs, but does it help if you clear the contents of the build folder and do `arch -x86_64 cmake ..` and `arch -x86_64 make`?

If that doesn't help, I can check if the issue can be reproduced on my x86 machine.

**Comment by eshitazaman** [comment]
Hi Tim,

I have tried the arch -x86_64 before cmake .. and make. This gives me the
following error which is almost same as the previous one:

bash-3.2$ arch -x86_64 cmake ..

arch: posix_spawnp: cmake: Bad CPU type in executable

bash-3.2$ arch -x86_64 make

make[2]: *** No rule to make target
`/Users/eshitazaman/storm/build/lib/libstorm-parsers.dylib', needed by
`storm-project-starter'.  Stop.

make[1]: *** [CMakeFiles/storm-project-starter.dir/all] Error 2

make: *** [all] Error 2


Thanks,

Eshita

**Comment by sjunges** [comment]
This error looks like your cmake version is not matching the specified x86 version.

**Comment by tquatmann** [comment]
[This page](https://www.stormchecker.org/documentation/obtain-storm/apple-silicon.html#cmake) is also relevant for the storm-project-starter

**Comment by eshitazaman** [comment]
Hi Tim and Sebastian,

I found the path to a x86_64 cmake installation (from homebrew); for
reference, it is: /usr/local/opt/cmake/bin/cmake. Where do I need to update
this path?

After I run ```arch -x86_64 /usr/local/opt/cmake/bin/cmake ..```, I still
get the same error of "No rule to make target" when I run make after.

Thank you.

Eshita

**Comment by tquatmann** [comment]
Hi Eshita,
if you get this message from `make`, it probably means that `cmake` already failed.

I think we're getting a bit off-topic for this (homebrew-related) issue.

Could you do the following and send us the *complete* chain of commands and output you get via support@stormchecker.org ?

- remove the `build` directory in your storm-project-starter-cpp and
- apply the steps from the `Readme.md` (using the x86_64  cmake and make(!) executables as mentioned before)

Best,
Tim
