### ISSUE TITLE
Error when installing using homebrew

### ISSUE THREAD

**Issue by rkay8496** [moves-rwth/homebrew-storm#5]
I am using apple mac os x 12.4. However, an error occurs when installing using homebrew.
<img width="723" alt="스크린샷 2022-07-09 오전 2 06 51" src="https://user-images.githubusercontent.com/946247/178038444-b71ee383-5da0-44db-8661-b203706a413b.png">

**Comment by volkm** [comment]
Are you using the ARM processer (M1)? There is no homebrew bottle available for cln on ARM (only for Intel).

**Comment by rkay8496** [comment]
Thanks for the reply. I'm using an M1 processor. Next, I will install it referring to "Additional steps for ARM-based Apple Silicon CPUs".

**Comment by volkm** [comment]
Yes, following [this guide](https://www.stormchecker.org/documentation/obtain-storm/apple-silicon.html) should make it work on the M1 processor for now.
